### ISSUE TITLE
Typo in conclusion

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/henry-david-thoreau_walden#2]
"Direct your eye right inward..." should be "Direct your eye sight inward..." apparently:

See: https://www.reddit.com/r/thoreau/comments/vnqgem/misprint_in_walden_direct_your_eye_right_inward/

**Comment by acabal** [comment]
Interesting, but we'd need more proof than a reddit post. Are there scans of the MS somewhere, or editions that make that change?

**Comment by acabal** [comment]
In the absence of any more evidence I'm going to close this. Let me know if you find something!
