### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/henry-david-thoreau_walden#5]
"...see how **it is** exhausted and debauched veins..."
should be
"...see how **his** exhausted and debauched veins..."

https://github.com/standardebooks/henry-david-thoreau_walden/blob/7df951997f1bffd13964f373345fb88dbbb7c159/src/epub/text/spring.xhtml#L52

https://archive.org/details/waldenorlifeinwo1854thor/page/336/mode/2up

**Comment by acabal** [comment]
Thanks, this should be fixed now!
